import React from "react";

const Footer = () => {
    return (
        <footer style={{ textAlign: "center", padding: "1rem", backgroundColor: "#f0f2f5" }}>
            <p>
                Open Source Survey Tool generated by{" "}
                <a href="https://openai.com/product/gpt-4" target="_blank" rel="noopener noreferrer">
                    ChatGPT-4
                </a>
                . Developed by{" "}
                <a href="https://github.com/lancerzhang/survey-ui" target="_blank" rel="noopener noreferrer">
                    YourName
                </a>{" "}
                on{" "}
                <a href="https://github.com/lancerzhang/survey-ui" target="_blank" rel="noopener noreferrer">
                    GitHub
                </a>
                .
            </p>
        </footer>
    );
};

export default Footer;
